// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive.dart';
import 'package:fitness_app/data/local/local_storage.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(CreateAccountAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(CreateAccountAdapter());
  }
}
