// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDjrKM_Ix3AtXdllF1BBzIS7be1WA2eu8o',
    appId: '1:634986070519:web:e1e8fa796a00be76672ef2',
    messagingSenderId: '634986070519',
    projectId: 'fitnessapptest-ef586',
    authDomain: 'fitnessapptest-ef586.firebaseapp.com',
    storageBucket: 'fitnessapptest-ef586.firebasestorage.app',
    measurementId: 'G-HGWDFCYZV7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBz8Iex0o-63CG8CGzQYtChDPRtEbek5ac',
    appId: '1:634986070519:android:a8c28d30b8fe3500672ef2',
    messagingSenderId: '634986070519',
    projectId: 'fitnessapptest-ef586',
    storageBucket: 'fitnessapptest-ef586.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC1Bt_kRO5zSS9fU5ShLNQN4lgqzsTlnmQ',
    appId: '1:634986070519:ios:b433248d6b987bcb672ef2',
    messagingSenderId: '634986070519',
    projectId: 'fitnessapptest-ef586',
    storageBucket: 'fitnessapptest-ef586.firebasestorage.app',
    iosBundleId: 'com.example.fitnessApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC1Bt_kRO5zSS9fU5ShLNQN4lgqzsTlnmQ',
    appId: '1:634986070519:ios:b433248d6b987bcb672ef2',
    messagingSenderId: '634986070519',
    projectId: 'fitnessapptest-ef586',
    storageBucket: 'fitnessapptest-ef586.firebasestorage.app',
    iosBundleId: 'com.example.fitnessApp',
  );
}
