name: fitness_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  openfoodfacts: ^3.25.1

  permission_handler: ^12.0.1

  image_picker: ^1.2.0

  health: ^13.1.4
  pedometer: ^4.1.1

  cloud_firestore: ^6.0.1
  firebase_core: ^4.1.0
  #firebase_storage: ^12.3.4
  firebase_auth: ^6.0.2

  hive_ce: ^2.12.0
  hive_ce_flutter: ^2.3.2

  hooks_riverpod: ^2.6.1
  flutter_hooks: ^0.21.3+1

  equatable: ^2.0.7

  flutter_animation_progress_bar: ^2.3.1
  percent_indicator: ^4.2.5
  font_awesome_flutter: ^10.10.0
  
  table_calendar: ^3.2.0

  fl_chart: ^1.1.0

  go_router: ^16.2.1

  json_annotation: ^4.9.0

  uuid: ^4.5.1

  device_info_plus: ^11.5.0

  fpdart: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  json_serializable: ^6.11.1
  build_runner: ^2.8.0
  #riverpod_test: ^0.1.9
  fake_cloud_firestore: ^4.0.0
  hive_ce_generator: ^1.9.5

flutter:
  uses-material-design: true
  #
  assets:
    - assets/images/



